version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: docx_converter_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-docx_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docx_password}
      POSTGRES_DB: ${POSTGRES_DB:-docx_converter_bot}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - docx_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-docx_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: docx_converter_bot
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      PROVIDER_TOKEN: ${PROVIDER_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
      FILE_PRICE: ${FILE_PRICE:-5000}
      POSTGRES_USER: ${POSTGRES_USER:-docx_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docx_password}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-docx_converter_bot}
    volumes:
      - ./files:/app/files
    networks:
      - docx_network

volumes:
  postgres_data:

networks:
  docx_network:
    driver: bridge
